version: "1.0"
services:
    app: #app container
        container_name: app
        restart: always
        build: ./api
        ports: 
            - "4000:4000"
        depends_on: 
            - mongo
    client:  #client container
        container_name: client
        restart: always
        build: ./client
        ports: 
            - "3000:3000"   
        depens_on:
            - app    
    mongo: #mongo container
        container_name: mongo
        image: mongo
        restart: always
        expose:
            - "27017"
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"